tar_test("inventory class is valid", {
  expect_silent(inventory_init()$validate())
})

tar_test("inventory abstract class basic methods", {
  x <- inventory_init()
  store <- store_init()
  store$file <- file_init(path = tempfile())
  writeLines("x", store$file$path)
  file_ensure_hash(store$file)
  expect_true(nzchar(store$file$hash))
  expect_equal(x$list(), character(0L))
  expect_equal(x$name(key = "x/y", bucket = "z"), "z|x/y")
})

tar_test("inventory abstract class null versions", {
  x <- inventory_init()
  store <- store_init()
  store$file <- file_init(path = tempfile())
  writeLines("x", store$file$path)
  file_ensure_hash(store$file)
  out <- x$get(key = "x/y", bucket = "z", version = NULL, store = store)
  out2 <- x$get(key = "x/y", bucket = "z", version = "abc123", store = store)
  expect_equal(out, out2)
  expect_equal(out, paste(store$file$hash, "prefix"))
  expect_equal(x$list(), "z|x/y")
  expect_silent(x$validate())
  x$reset()
  expect_equal(x$list(), character(0L))
  expect_silent(x$validate())
})

tar_test("inventory abstract class null versions", {
  x <- inventory_init()
  store <- store_init()
  store$file <- file_init(path = tempfile())
  writeLines("x", store$file$path)
  file_ensure_hash(store$file)
  out <- x$get(key = "x/y", bucket = "z", version = "abc123", store = store)
  out2 <- x$get(key = "x/y", bucket = "z", version = NULL, store = store)
  expect_equal(out, out2)
  expect_equal(out, paste(store$file$hash, "key"))
  expect_equal(x$list(), "z|x/y")
  expect_silent(x$validate())
  x$reset()
  expect_equal(x$list(), character(0L))
  expect_silent(x$validate())
})
