tar_test("config$validate()", {
  path <- tempfile()
  out <- config_init(path)
  expect_silent(out$validate())
  file.create(path)
  expect_silent(out$validate())
  out$ensure()
  expect_silent(out$validate())
  out$set_store("x")
  expect_silent(out$validate())
})

tar_test("config$validate() with bad store", {
  path <- tempfile()
  out <- config_init(path)
  writeLines("store: 123", path)
  out$ensure()
  expect_error(out$validate(), class = "tar_condition_validate")
})

tar_test("config$get_store() and config$set_store()", {
  path <- tempfile()
  out <- config_init(path = path)
  expect_equal(out$get_store(), path_store_default())
  out$set_store("x")
  lines <- readLines(path)
  expect_equal(lines, "store: x")
  expect_equal(out$get_store(), "x")
  expect_error(out$set_store(123), class = "tar_condition_validate")
})

tar_test("config$set_path()", {
  path <- tempfile()
  path2 <- tempfile()
  out <- config_init(path = path)
  expect_equal(out$get_path(), path)
  expect_equal(out$get_script(), path_script_default())
  out$set_script("x")
  expect_equal(out$get_script(), "x")
  out$set_path(path2)
  expect_equal(out$get_path(), path2)
  expect_equal(out$get_script(), path_script_default())
})

tar_test("config$assign_script()", {
  path <- tempfile()
  out <- config_init(path = path)
  expect_equal(out$get_script(), path_script_default())
  out$assign_script("x")
  out$set_lock()
  expect_false(file.exists(path))
  expect_equal(out$get_script(), "x")
})

tar_test("config$assign_store()", {
  path <- tempfile()
  out <- config_init(path = path)
  expect_equal(out$get_store(), path_store_default())
  out$assign_store("x")
  out$set_lock()
  expect_false(file.exists(path))
  expect_equal(out$get_store(), "x")
})

tar_test("config$get_script() and config$set_script()", {
  path <- tempfile()
  out <- config_init(path = path)
  expect_equal(out$get_script(), path_script_default())
  out$set_script("x")
  lines <- readLines(path)
  expect_equal(lines, "script: x")
  expect_equal(out$get_script(), "x")
  expect_error(out$set_script(123), class = "tar_condition_validate")
})

tar_test("config$get_value()", {
  path <- tempfile()
  out <- config_init(path = path)
  expect_null(out$get_value("store"))
  writeLines("store: path", path)
  expect_equal(out$get_value("store"), "path")
  expect_equal(out$get_value("store"), "path")
  writeLines("store: path2", path)
  expect_equal(out$get_value("store"), "path2")
  unlink(path)
  expect_null(out$get_value("store"))
  writeLines("store: path3", path)
  expect_equal(out$get_value("store"), "path3")
})

tar_test("config$set_value() on an empty _targets.yaml", {
  path <- tempfile()
  out <- config_init(path = path)
  out$set_value(name = "store", "path2")
  expect_equal(out$get_value("store"), "path2")
  expect_true(any(grepl("path2", readLines(path))))
})

tar_test("config$set_value() on a _targets.yaml with other settings", {
  path <- tempfile()
  lines <- c("store: path1", "other: value")
  writeLines(lines, path)
  out <- config_init(path = path)
  out$set_value(name = "store", "path2")
  expect_equal(out$get_value("store"), "path2")
  lines <- readLines(path)
  expect_true(any(grepl("path2", readLines(path))))
  expect_true(any(grepl("value", readLines(path))))
})

tar_test("locking", {
  path <- tempfile()
  out <- config_init(path = path)
  out$set_value(name = "store", "path2")
  expect_equal(out$get_value("store"), "path2")
  out$set_lock()
  expect_equal(out$get_value("store"), "path2")
  out$set_value(name = "store", "path3")
  expect_equal(out$get_value("store"), "path2")
  expect_true(any(grepl("path2", readLines(path))))
  writeLines("store: path3", path)
  expect_equal(out$get_value("store"), "path2")
  out$unset_lock()
  expect_equal(out$get_value("store"), "path3")
  out$set_value(name = "store", "path4")
  expect_true(any(grepl("path4", readLines(path))))
  expect_equal(out$get_value("store"), "path4")
})

tar_test("export", {
  path <- tempfile()
  out <- config_init(path = path)
  out$set_value(name = "store", "path2")
  expect_equal(out$get_value("store"), "path2")
  out$set_lock()
  out <- out$export()
  exp <- list(
    path = path,
    data = list(store = "path2"),
    lock = TRUE
  )
  expect_equal(out, exp)
})

tar_test("import a config", {
  path <- tempfile()
  path2 <- tempfile()
  out <- config_init(path = path)
  out2 <- config_init(path = path2)
  out$set_value(name = "store", "path2")
  expect_equal(out$get_value("store"), "path2")
  out$set_lock()
  expect_equal(out2$path, path2)
  expect_equal(out2$data, NULL)
  expect_equal(out2$lock, NULL)
  out2$import(out)
  expect_equal(out2$path, path)
  expect_equal(out2$data, list(store = "path2"))
  expect_equal(out2$lock, TRUE)
})

tar_test("import an exported list", {
  path <- tempfile()
  path2 <- tempfile()
  out <- config_init(path = path)
  out2 <- config_init(path = path2)
  out$set_value(name = "store", "path2")
  expect_equal(out$get_value("store"), "path2")
  out$set_lock()
  expect_equal(out2$path, path2)
  expect_equal(out2$data, NULL)
  expect_equal(out2$lock, NULL)
  out2$import(out$export())
  expect_equal(out2$path, path)
  expect_equal(out2$data, list(store = "path2"))
  expect_equal(out2$lock, TRUE)
})
