tar_test("crew$validate()", {
  skip_if_not_installed("crew")
  controller <- crew::crew_controller_local()
  out <- crew_init(pipeline_init(), controller = controller)
  expect_silent(out$validate())
})

tar_test("workerless deployment works", {
  skip_cran()
  skip_on_os("windows")
  skip_on_os("solaris")
  skip_if_not_installed("crew")
  tar_runtime$set_fun("tar_make")
  on.exit(tar_runtime$unset_fun())
  on.exit(crew_test_sleep(), add = TRUE)
  x <- tar_target_raw("x", quote(1L), deployment = "main")
  y <- tar_target_raw("y", quote(x), deployment = "main")
  z <- tar_target_raw("z", quote(x + 1L), deployment = "main")
  pipeline <- pipeline_init(list(x, y, z))
  controller <- crew::crew_controller_local()
  crew_init(pipeline, controller = controller)$run()
  expect_equal(target_read_value(x)$object, 1L)
  expect_equal(target_read_value(y)$object, 1L)
  expect_equal(target_read_value(z)$object, 2L)
  x <- tar_target_raw("x", quote(1L), deployment = "main")
  y <- tar_target_raw("y", quote(x), deployment = "main")
  z <- tar_target_raw("z", quote(x + 1L), deployment = "main")
  pipeline <- pipeline_init(list(x, y, z))
  out <- crew_init(pipeline)
  out$run()
  built <- names(out$scheduler$progress$built$envir)
  expect_equal(built, character(0))
})

tar_test("semi-workerless deployment works", {
  skip_cran()
  skip_on_os("windows")
  skip_on_os("solaris")
  skip_if_not_installed("crew")
  crew_test_sleep()
  tar_runtime$set_fun("tar_make")
  on.exit(tar_runtime$unset_fun())
  on.exit(crew_test_sleep(), add = TRUE)
  x <- tar_target_raw("x", quote(1L), deployment = "main")
  y <- tar_target_raw("y", quote(x), deployment = "worker")
  z <- tar_target_raw("z", quote(x + 1L), deployment = "main")
  pipeline <- pipeline_init(list(x, y, z))
  controller <- crew::crew_controller_local()
  crew_init(pipeline, controller = controller)$run()
  expect_equal(target_read_value(x)$object, 1L)
  expect_equal(tar_read(y), 1L)
  expect_equal(target_read_value(z)$object, 2L)
  x <- tar_target_raw("x", quote(1L), deployment = "main")
  y <- tar_target_raw("y", quote(x), deployment = "worker")
  z <- tar_target_raw("z", quote(x + 1L), deployment = "main")
  pipeline <- pipeline_init(list(x, y, z))
  controller <- crew::crew_controller_local()
  out <- crew_init(pipeline, controller = controller)
  out$run()
  built <- names(out$scheduler$progress$built$envir)
  expect_equal(built, character(0))
})

tar_test("some targets up to date, some not", {
  skip_cran()
  skip_on_os("windows")
  skip_on_os("solaris")
  skip_if_not_installed("crew")
  crew_test_sleep()
  tar_runtime$set_fun("tar_make")
  on.exit(tar_runtime$unset_fun())
  on.exit(crew_test_sleep(), add = TRUE)
  x <- tar_target_raw("x", quote(1L))
  y <- tar_target_raw("y", quote(x))
  pipeline <- pipeline_init(list(x, y))
  local <- local_init(pipeline)
  local$run()
  x <- tar_target_raw("x", quote(1L))
  y <- tar_target_raw("y", quote(x + 1L))
  pipeline <- pipeline_init(list(x, y))
  controller <- crew::crew_controller_local()
  algo <- crew_init(pipeline, controller = controller)
  algo$run()
  out <- names(algo$scheduler$progress$built$envir)
  expect_equal(out, "y")
  value <- target_read_value(pipeline_get_target(pipeline, "y"))
  expect_equal(value$object, 2L)
})

tar_test("crew algo can skip targets", {
  skip_cran()
  skip_on_os("windows")
  skip_on_os("solaris")
  skip_if_not_installed("crew")
  tar_runtime$set_fun("tar_make")
  on.exit(tar_runtime$unset_fun())
  on.exit(crew_test_sleep(), add = TRUE)
  x <- tar_target_raw("x", quote(1L))
  y <- tar_target_raw("y", quote(x))
  pipeline <- pipeline_init(list(x, y))
  local <- local_init(pipeline)
  local$run()
  unlink(file.path("_targets", "objects", "x"))
  x <- tar_target_raw("x", quote(1L))
  y <- tar_target_raw("y", quote(x))
  pipeline <- pipeline_init(list(x, y))
  controller <- crew::crew_controller_local()
  algo <- crew_init(pipeline, controller = controller)
  algo$run()
  out <- names(algo$scheduler$progress$built$envir)
  expect_equal(out, "x")
  expect_equal(tar_read(x), 1L)
})

tar_test("nontrivial common data", {
  skip_cran()
  skip_on_os("windows")
  skip_on_os("solaris")
  skip_if_not_installed("crew")
  tar_runtime$set_fun("tar_make")
  on.exit(tar_runtime$unset_fun())
  on.exit(crew_test_sleep(), add = TRUE)
  old_envir <- tar_option_get("envir")
  envir <- new.env(parent = globalenv())
  tar_option_set(envir = envir)
  on.exit(tar_option_set(envir = old_envir), add = TRUE)
  evalq({
    f <- function(x) {
      g(x) + 1L
    }
    g <- function(x) {
      x + 1L
    }
  }, envir = envir)
  x <- tar_target_raw("x", quote(f(1L)))
  pipeline <- pipeline_init(list(x))
  controller <- crew::crew_controller_local()
  algo <- crew_init(pipeline, controller = controller)
  algo$run()
  value <- target_read_value(pipeline_get_target(pipeline, "x"))
  expect_equal(value$object, 3L)
})

tar_test("crew with a dynamic file", {
  skip_cran()
  skip_on_os("windows")
  skip_on_os("solaris")
  skip_if_not_installed("crew")
  tar_runtime$set_fun("tar_make")
  on.exit(tar_runtime$unset_fun())
  on.exit(crew_test_sleep(), add = TRUE)
  old_envir <- tar_option_get("envir")
  envir <- new.env(parent = globalenv())
  on.exit(tar_option_set(envir = old_envir), add = TRUE)
  tar_option_set(envir = envir)
  evalq({
    save1 <- function() {
      file <- "saved.out"
      saveRDS(1L, file)
      file
    }
  }, envir = envir)
  x <- tar_target_raw("x", quote(save1()), format = "file")
  pipeline <- pipeline_init(list(x))
  controller <- crew::crew_controller_local()
  algo <- crew_init(pipeline, controller = controller)
  algo$run()
  out <- names(algo$scheduler$progress$built$envir)
  expect_equal(out, "x")
  saveRDS(2L, pipeline_get_target(pipeline, "x")$store$file$path)
  x <- tar_target_raw("x", quote(save1()), format = "file")
  pipeline <- pipeline_init(list(x))
  controller <- crew::crew_controller_local()
  algo <- crew_init(pipeline, controller = controller)
  algo$run()
  out <- names(algo$scheduler$progress$built$envir)
  expect_equal(out, "x")
})

tar_test("crew with a dynamic file", {
  skip_cran()
  skip_on_os("windows")
  skip_on_os("solaris")
  skip_if_not_installed("crew")
  tar_runtime$set_fun("tar_make")
  on.exit(tar_runtime$unset_fun())
  on.exit(crew_test_sleep(), add = TRUE)
  old_envir <- tar_option_get("envir")
  envir <- new.env(parent = globalenv())
  on.exit(tar_option_set(envir = old_envir), add = TRUE)
  tar_option_set(envir = envir)
  evalq({
    save1 <- function() {
      file <- "saved.out"
      saveRDS(1L, file)
      file
    }
  }, envir = envir)
  x <- tar_target_raw("x", quote(save1()), format = "file")
  pipeline <- pipeline_init(list(x))
  controller <- crew::crew_controller_local()
  algo <- crew_init(pipeline, controller = controller)
  algo$run()
  out <- names(algo$scheduler$progress$built$envir)
  expect_equal(out, "x")
  saveRDS(2L, pipeline_get_target(pipeline, "x")$store$file$path)
  x <- tar_target_raw("x", quote(save1()), format = "file")
  pipeline <- pipeline_init(list(x))
  controller <- crew::crew_controller_local()
  algo <- crew_init(pipeline, controller = controller)
  algo$run()
  out <- names(algo$scheduler$progress$built$envir)
  expect_equal(out, "x")
})
