tar_test("yaml$validate()", {
  out <- yaml_init()
  expect_silent(out$validate())
  file.create("_targets.yaml")
  expect_silent(out$validate())
  out$ensure()
  expect_silent(out$validate())
})

tar_test("yaml$store()", {
  out <- yaml_init(path = "_targets.yaml")
  expect_null(out$store())
  writeLines("store: path", "_targets.yaml")
  expect_equal(out$store(), "path")
  expect_equal(out$store(), "path")
  writeLines("store: path2", "_targets.yaml")
  expect_equal(out$store(), "path2")
  unlink("_targets.yaml")
  expect_null(out$store())
  writeLines("store: path3", "_targets.yaml")
  expect_equal(out$store(), "path3")
})

tar_test("path_store() with yaml$store()", {
  expect_equal(path_store(), "_targets")
  writeLines("store: path", "_targets.yaml")
  expect_equal(path_store(), "path")
  expect_equal(path_store(), "path")
  writeLines("store: path2", "_targets.yaml")
  expect_equal(path_store(), "path2")
  unlink("_targets.yaml")
  expect_equal(path_store(), "_targets")
  writeLines("store: path3", "_targets.yaml")
  expect_equal(path_store(), "path3")
})
