tar_test("tar_renv() works", {
  expect_false(file.exists("_packages.R"))
  tar_script({
    tar_option_set(packages = c("tibble", "qs")); tar_pipeline()
    })
  tar_renv()
  expect_true(file.exists("_packages.R"))
  expect_equal(
    readLines("_packages.R"),
    c(
      "# Generated by targets::tar_renv(): do not edit by hand",
      paste0("library(", c("clustermq", "future", "qs", "rstudioapi",
                           "tibble", "visNetwork"), ")")
      )
    )
})

tar_test("tar_renv() works with custom path", {
  path <- tempfile()
  expect_false(file.exists(path))
  tar_script({
    tar_option_set(packages = c("tibble", "qs")); tar_pipeline()
    })
  tar_renv(path = path)
  expect_true(file.exists(path))
  expect_equal(
    readLines(path),
    c(
      "# Generated by targets::tar_renv(): do not edit by hand",
      paste0("library(", c("clustermq", "future", "qs", "rstudioapi",
                           "tibble", "visNetwork"), ")")
    )
  )
})
