# Generated by targets: do not edit by hand
library(targets)
lapply(
  list.files(
    file.path("PATH_SCRIPT_R", "globals"),
    pattern = "\\.R$",
    full.names = TRUE
  ),
  source
)
lapply(
  list.files(
    file.path("PATH_SCRIPT_R", "targets"),
    pattern = "\\.R$",
    full.names = TRUE
  ),
  function(x) source(x)$value
)
