# Generated by Target Markdown in targets 0.4.2.9000: do not edit by hand
library(targets)
lapply(
  list.files(
    "_targets_r/globals",
    pattern = "\\.R$",
    full.names = TRUE
  ),
  source
)
lapply(
  list.files(
    "_targets_r/targets",
    pattern = "\\.R$",
    full.names = TRUE
  ),
  function(x) source(x)$value
)
