#' @title Set up package dependencies for compatibility with `renv`
#' @export
#' @description Write package dependencies to a file named `_packages.R` in
#'   the root project directory. Each package is written to a separate line in
#'   `_packages.R` as a standard [`library`] call (e.g. `library(package)`)
#'   so that they may be identified by `{renv}` for caching. This is only
#'   necessary if the user invokes [`tar_option_set()`] or [`tar_target()`] to
#'   declare packages rather than [`library`]/[`require`] or namespacing
#'   (i.e. `package::function()`). See `Details` for more information.
#' @details This function gets called for its side-effect, which writes
#'   package dependencies provided to the `packages` argument to
#'   `_packages.R`. `tar_renv()` is unable to detect packages declared after it
#'   has been called in the script (e.g. target-specific packages declared
#'   within [`tar_pipeline`]); these packages need to be
#'   passed to `tar_renv()` manually. The generated file should __not__ be
#'   edited by hand and will be overwritten each time `tar_renv()` runs.
#'
#'   By explicitly writing packages to a file, `{renv}` is able to crawl the
#'   file to identify package dependencies with [`renv::dependencies()`].
#'   Calling [`renv::init()`] after `tar_renv()` has ran will set up a
#'   project-local `R` library. This allows your `targets` pipeline to have
#'   its own self-contained `R` library separate from your standard `R`
#'   library. See [`{renv}`](https://rstudio.github.io/renv/index.html) for
#'   more information.
#'
#'   During interactive project development, you may find it useful to run
#'   `source("_packages.R")` to quickly load packages. However, this file
#'   primarily exists to provide native compatibility with `{renv}`.
#' @inheritParams tar_option_set
#' @param ask Logical, whether to ask before writing if `_packages.R`
#'   already exists. If `NULL`, defaults to `Sys.getenv("TAR_ASK")`.
#'   (Set to `"true"` or `"false"` with `Sys.setenv()`).
#'   If `ask` and the `TAR_ASK` environment variable are both
#'   indeterminate, defaults to `interactive()`.
#' @seealso <https://rstudio.github.io/renv/articles/renv.html>
#' @md
#' @return Nothing, invisibly.
#' @examples
#' tar_dir({
#'   pkgs <- c("tidyverse", "qs")
#'   tar_option_set(packages = pkgs)
#'   tar_renv()
#'   readLines("_packages.R")
#' })
tar_renv <- function(
  packages = targets::tar_option_get("packages"),
  ask = NULL
  ) {
  if (!tar_should_overwrite(ask, "_packages.R")) {
    return(invisible()) #nocov
  }
  lines <- c(
  "# Generated by targets::tar_env: do not edit by hand",
  paste0("library(", packages, ")")
  )
  writeLines(lines, con = "_packages.R")
  return(invisible())
}
